### PR TITLE
Added parameter $parentsController to the removeParentMethods() method

### PR DESCRIPTION
**Pull request by leodisarli**
Added parameter $parentsController to the removeParentMethods() method
to add multiples parents controllers.

### CODE REVIEW

**Comment by cakebaker** [comment]
Thanks for your pull request.

I think the comment inside the method is a sign of a code smell because having to touch the component's source to configure it is not that clean.  It's probably better to use CakePHP's approach for configuring components that allows you to configure a component when adding it to the <code>$components</code> array.

**Comment by leodisarli** [comment]
Agreed! I think you're right. You think I must change the code to the component receive an array of parents controllers too? Or just cancel PR? Thanks for the component, and cheers from Brazil (sorry about my english too.) Bests regards!

**Comment by cakebaker** [comment]
Ok, I added the feature in https://github.com/cakebaker/controller-list-component/commit/ad8b70df54f2aa36addd09e30e7a007c05f307df. You can now define the parent controllers in the following way:
```php
public $components = array('ControllerList' => array('parentControllers' => array('AppController', 'ParentController')));
```

**Comment by leodisarli** [comment]
Thank you! And congrats for the component! Cheers!
Em 17/11/2015 08:12, "Daniel Hofstetter" <notifications@github.com>
escreveu:

**Pull request closed without merging**
